### PR TITLE
Add sample group link

### PR DESCRIPTION
**Pull request by TheBeachMaster**
- Great idea 
- I have the following suggestions : 
  - Groups to be placed in individual folders
  - Links are markdown content
  - Add links to WhatsApp, Telegram, Slack, IRC, Gitter etc
  - Adding shields is awesome → http://shields.io/

### CODE REVIEW

**Comment by ikuamike** [comment]
Should have opened this one as an issue, suggestion noted

**Review by ikuamike — CHANGES_REQUESTED** [review]
change the ml_ai.md to readme.md so it's readable once the folder is loaded

**Comment by TheBeachMaster** [comment]
Close PR. 

IMHO, it'll be good to have groups in folders, having everything in the README would make all the links messy.

Structured as follows: 
```
.../JavaScript
.../.NET
.../AI_ML
.../AI_ML/ai_ml.md  ## Links to all AI/ML groups
.../IOT 
...etc 
...README.md  ## Has link to folders above
```

**Comment by TheBeachMaster** [comment]
LGTM. 
Closing.

**Comment by ikuamike** [comment]
This layout is good look what I did with the University Tech Groups, In the folder each group has it's md that contains everything and is linked from the main readme. I think it's better to separate them.

**Comment by ikuamike** [comment]
This is a better structure 
```
.../JavaScript
.../.NET
.../AI_ML
.../AI_ML/Nairobi_ML_Community.md   ## Every group to have its own file that has all links and resources
.../IOT 
...etc 
...README.md  ## Has all groups listed and links to their markdown file is here
```

**Comment by TheBeachMaster** [comment]
Make sense.

Will sync my repo and make new PR

**Pull request closed without merging**
